version: "3"

services:
  mongodb:
    image: mongo:latest
    environment:
      - MONGODB_DATABASE="test"
    ports:
      - 27017:27017

  redis:
    image: redis:latest
    ports:
      - 6379:6379